# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
SENDGRID_PASSWORD: ctutlz5b
SENDGRID_USERNAME: app35501721@heroku.com
SECRET_KEY_BASE: 2bcac953c8f547e75edb1aee46f7e0583d6b9d86a1b3ec52a349a68b52c2cd14e266d4af44c50402e1cf53bc1e8f50f637e96c66faaeff8dc06490046229775a
AWS_ACCESS_KEY_ID: AKIAI6LWBSW3SWG7MGIA
AWS_SECRET_ACCESS_KEY: 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
development:
  AWS_BUCKET: cheryltroup-bloccit-developement
production:
  AWS_BUCKET: cheryltroup-bloccit-production